spring:
  application:
    name: tradecore

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.alexsandroandre.tradecore: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.alexsandroandre.tradecore: DEBUG

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.alexsandroandre.tradecore: INFO